### ISSUE TITLE
Portuguese Translation Update

### ISSUE THREAD

**Issue by sergiopjf** [JaredDC/DailyWallpaper#3]
[portuguese.txt](https://github.com/JaredDC/DailyWallpaper/files/8951476/portuguese.txt)
<pt>
    <UI_FontFamily>Segoe UI</UI_FontFamily>
    <DRAW_FontFamily>Segoe UI</DRAW_FontFamily>
    <APP_START>O DailyWallpaper está sendo executado em segundo plano.</APP_START>
    <APP_SECOND>O DailyWallpaper já está em execução</APP_SECOND>
    <APP_PATH_NOT_WRITABLE>O caminho de dados "{0}"não é gravável. Verifique se você tem permissão suficiente.</APP_PATH_NOT_WRITABLE>
    <Update_NoUpdate>Você está usando a versão mais recente.</Update_NoUpdate>
    <Update_Found>DailyWallpaper {0} foi lançado. Clique aqui para abrir a página de download.</Update_Found>
    <Update_Error>Ocorreu um erro ao verificar atualizações: {0}</Update_Error>
    <Icon_RunAtStartup>Executar na inicialização</Icon_RunAtStartup>
    <Icon_ToolTip>DailyWallpaper v{0}</Icon_ToolTip>
    <Icon_ChangeWallpaper>Trocar o papel de parede</Icon_ChangeWallpaper>
    <Icon_ChangeWallpaperTit>Clique, selecione aleatoriamente na lista marcada e altere o papel de parede</Icon_ChangeWallpaperTit>
    <Icon_Bing>Bing</Icon_Bing>
    <Icon_LocalPath>Pasta local</Icon_LocalPath>
    <Icon_LocalPathSetting>Configuração de pasta local</Icon_LocalPathSetting>
    <Icon_Spotlight>Windows Spotlight</Icon_Spotlight>
    <Icon_DisableShortcutKeys>Desativar teclas de atalho</Icon_DisableShortcutKeys>
    <Icon_Options>Opções...</Icon_Options>
    <Icon_DonateAndSupport>Doe e apoie...</Icon_DonateAndSupport>
    <Icon_Help>Ajuda</Icon_Help>
    <Icon_OpenOfficialWebsite>Abrir o site oficial..</Icon_OpenOfficialWebsite>
    <Icon_CheckUpdate>Procurar por atualizações</Icon_CheckUpdate>
    <Icon_IssueAndFeedback>Problemas e feedback...</Icon_IssueAndFeedback>
    <Icon_ShowLog>Abra a janela do console</Icon_ShowLog>
    <Icon_About>Sobre</Icon_About>
    <Icon_Quit>Sair</Icon_Quit>
    <TrayIcon_ShortcutKeys>(Clique duas vezes no ícone da bandeja)</TrayIcon_ShortcutKeys>
    <Notify_SetWallpaper_Succeed>Papel de parede definido com sucesso: </Notify_SetWallpaper_Succeed>
    <Notify_SetWallpaper_Failed>Falha ao definir o papel de parede, clique aqui para ver o que acontece ou em Ajuda -> Mostrar registro</Notify_SetWallpaper_Failed>
    <Notify_LocalPathSetting>Selecionei esta pasta: </Notify_LocalPathSetting>
    <Notify_ThanksForDonation>Obrigado por seu apoio!</Notify_ThanksForDonation>
    <Notify_RunAtStartup> Parabéns! você ativou a função de execução automática na inicialização. {0}Isso lhe dará uma experiência melhor!</Notify_RunAtStartup>
    <Icon_AutoChangeWallpaper>Trocar o papel de parede a cada</Icon_AutoChangeWallpaper>
    <Icon_Unit>horas</Icon_Unit>
    <Icon_Custom>Person...</Icon_Custom>
    <Icon_AlwaysDownLoadBingPicture>Sempre baixar a imagem do Bing</Icon_AlwaysDownLoadBingPicture>
    <Icon_BingNotAddWaterMark>Não adicionar marca d'água ao Bing</Icon_BingNotAddWaterMark>
    <Notify_AtLeastSelectOneFeature>Selecione pelo menos uma opção, como: Windows Spotlight</Notify_AtLeastSelectOneFeature>
    <Icon_CleanEmptyFolders>LImpar pastas vazias</Icon_CleanEmptyFolders>
    <Icon_HashCalc>Calcular Hash</Icon_HashCalc>
    <Icon_Notepad>Abrir NotePad++/Notepad</Icon_Notepad>
    <Icon_Toolbox>Caixa de Ferramentas</Icon_Toolbox>
    <Icon_FeatureTit>adicionar {0} para lista aleatória</Icon_FeatureTit>
    <Icon_DeleteCurrentWallpaper>Excluir</Icon_DeleteCurrentWallpaper>
    <Icon_CleanUnqualifiedImages>Limpar imagens não qualificadas</Icon_CleanUnqualifiedImages>
    <Notify_CleanUnqualifiedPicturesConfirm>Imagens não qualificadas serão excluídas, clique OK para continuar!</Notify_CleanUnqualifiedPicturesConfirm>
    <Icon_Gemini>Gemini</Icon_Gemini>
    <Icon_ShutdownTimer>Temporizador de desligamento</Icon_ShutdownTimer>
    <Icon_DateCalc>Calculadora de data</Icon_DateCalc>
    <Icon_LikeCurrentWallpaper>Curti</Icon_LikeCurrentWallpaper>
    <Icon_ForceUpdate>Forcar atualização</Icon_ForceUpdate>
    <Icon_RegularUpdate>Atualização regular</Icon_RegularUpdate>
    <Icon_CheckUpdateFrequency>Frequência de verificação de atualização</Icon_CheckUpdateFrequency>
    <Icon_AutoCheckUpdateFreq>Frequência de verificação automática de atualização</Icon_AutoCheckUpdateFreq>
    <Icon_EmptyRecycleBin>Esvaziar a lixeira</Icon_EmptyRecycleBin>
    <Icon_ScanQRCode>Escanear QR Code</Icon_ScanQRCode>
    <Notify_ScanResult>Resultado do escaneamento: </Notify_ScanResult>
    <Notify_QRCodeNotDetected>QR Code não detectado!</Notify_QRCodeNotDetected>
    <Notify_CopiedToClipboard>Copiado para a área de transferência...</Notify_CopiedToClipboard>
    <Notify_EmptyRecycleBinSucceed>Lixeira esvaziada com sucesso.</Notify_EmptyRecycleBinSucceed>
  </pt>

**Comment by uvery9** [comment]
Updated, thanks for the contribution
